"""Rewrite generator: produce proposed rewrites for weak artifacts.

Implements Core Requirement 10.

Rewrite triggers (any of):
- missing metadata
- vague contracts
- high token cost
- over-broad responsibility
- high overlap
- low ROI
- poor benchmark score

Generated output: output/proposed_rewrites/{artifact_name}.rewrite.md

Each rewrite must include:
- improved metadata
- tighter purpose
- explicit inputs
- explicit outputs
- reduced redundancy
- token-efficient instructions
- clear boundaries
- validation expectations
- compatibility notes
- migration notes
"""
from __future__ import annotations

import re
from pathlib import Path

from .models import (
    BenchmarkResult,
    Decision,
    Finding,
    ResponsibilityReport,
    ScorecardEntry,
    Severity,
    SkillArtifact,
)


def _sanitize_name(name: str) -> str:
    """Convert an artifact name to a safe filename."""
    return re.sub(r"[^A-Za-z0-9._-]", "_", name)


def _identify_triggers(
    artifact: SkillArtifact,
    findings: list[Finding],
    scorecard: ScorecardEntry | None,
    responsibility: ResponsibilityReport | None,
    benchmark: BenchmarkResult | None,
) -> list[str]:
    """Return a list of rewrite triggers (e.g. 'missing-metadata')."""
    triggers: list[str] = []
    own_findings = [f for f in findings if f.artifact_name == artifact.name]
    if any(f.category == "metadata" and f.severity == Severity.BLOCKING for f in own_findings):
        triggers.append("missing-metadata")
    if any(f.category == "contract" and f.severity == Severity.BLOCKING for f in own_findings):
        triggers.append("vague-contracts")
    if artifact.estimated_tokens >= 8000:
        triggers.append("high-token-cost")
    if responsibility and responsibility.flag.value == "over-broad":
        triggers.append("over-broad-responsibility")
    if scorecard and scorecard.decision in (Decision.REWRITE, Decision.MERGE, Decision.SPLIT):
        triggers.append(f"roi-decision-{scorecard.decision.value}")
    if benchmark and not benchmark.passed:
        triggers.append("benchmark-failure")
    return triggers


def _build_metadata_block(artifact: SkillArtifact) -> str:
    """Build an improved YAML metadata block for a rewrite."""
    name = artifact.name.split("/")[-1] if "/" in artifact.name else artifact.name
    return f"""---
name: {name}
artifact_type: {artifact.artifact_type.value}
purpose: |
  Tighten this 1-2 sentence purpose: who uses this skill,
  what it does, and in what context.
category: {artifact.category or "TBD"}
owner: {artifact.owner or "TBD"}
version: "0.2.0"
inputs:
  - name: input_data
    type: file
    description: Describe the expected input shape.
outputs:
  format: json
  fields:
    - result
    - evidence
dependencies: []
intended_consumers: []
quality_level: draft
last_reviewed: 2026-06-13
---"""


def _build_compatibility_notes(artifact: SkillArtifact) -> str:
    """Compatibility / migration notes."""
    return f"""## Compatibility and migration

- The original artifact was `{artifact.name}` (type: `{artifact.artifact_type.value}`).
- This rewrite preserves the original's intent but tightens scope.
- Consumers of the original should not see a behavioral change in
  the happy path; only the metadata contract is now stricter.
- To migrate:
  1. Replace the original file with this rewrite.
  2. Add the missing metadata fields to your local copy.
  3. Re-run `skill-governance validate` to confirm CI passes.
"""


def _build_rewrite_body(
    artifact: SkillArtifact,
    triggers: list[str],
) -> str:
    """Build the body of the rewrite (after the metadata block)."""
    name = artifact.name.split("/")[-1] if "/" in artifact.name else artifact.name
    lines: list[str] = []
    lines.append(f"# {name} (rewrite proposal)\n")
    lines.append("> This file was generated by the `rewrite_generator` module. ")
    lines.append("It is a *proposal*, not an automatic replacement. Review the ")
    lines.append("changes, then either accept them or refine the rewrite.\n")
    lines.append("## Why this rewrite was triggered\n")
    for t in triggers:
        lines.append(f"- `{t}`")
    lines.append("")
    lines.append("## What changed\n")
    lines.append("1. **Metadata** is now a complete YAML frontmatter block with all required fields.")
    lines.append("2. **Inputs** are declared as a list of named fields (not free-text).")
    lines.append("3. **Outputs** declare an explicit `format` and a `fields` list.")
    lines.append("4. **Boundaries** are explicit: this skill does one thing, in one context, for one consumer.")
    lines.append("5. **Validation expectations** are concrete (see below).")
    lines.append("")
    lines.append("## Token efficiency\n")
    if artifact.estimated_tokens > 0:
        lines.append(f"- Original estimated tokens: {artifact.estimated_tokens}")
    lines.append("- Rewrite target: keep under 2,000 tokens for a single-purpose skill.")
    lines.append("- If you need more, this is a sign that the skill is over-broad (consider splitting).")
    lines.append("")
    lines.append("## Validation expectations\n")
    lines.append("- `skill-governance validate` should pass with no blocking findings.")
    lines.append("- The metadata parser should extract all 12 required fields.")
    lines.append("- The contract validator should not flag vague outputs.")
    lines.append("- If a benchmark exists for this skill, the runner should report `passed=true`.")
    lines.append("")
    lines.append("## Original excerpt\n")
    if artifact.body_excerpt:
        excerpt = artifact.body_excerpt[:500]
        lines.append("```")
        lines.append(excerpt)
        lines.append("```")
    else:
        lines.append("(no original body was available)")
    lines.append("")
    return "\n".join(lines)


def generate_rewrite(
    artifact: SkillArtifact,
    findings: list[Finding],
    scorecard: ScorecardEntry | None = None,
    responsibility: ResponsibilityReport | None = None,
    benchmark: BenchmarkResult | None = None,
) -> str | None:
    """Generate a proposed rewrite for one artifact.

    Returns the proposed body, or `None` if there are no rewrite
    triggers (the artifact doesn't need a rewrite).
    """
    triggers = _identify_triggers(artifact, findings, scorecard, responsibility, benchmark)
    if not triggers:
        return None
    metadata = _build_metadata_block(artifact)
    body = _build_rewrite_body(artifact, triggers)
    compat = _build_compatibility_notes(artifact)
    return f"{metadata}\n\n{body}\n{compat}\n"


def generate_rewrites(
    artifacts: list[SkillArtifact],
    findings: list[Finding],
    scorecards: list[ScorecardEntry] | None = None,
    responsibility: list[ResponsibilityReport] | None = None,
    benchmark_results: list[BenchmarkResult] | None = None,
    output_dir: Path | None = None,
) -> dict[str, str]:
    """Generate proposed rewrites for every artifact that needs one.

    Returns a mapping of artifact_name -> proposed body.

    If `output_dir` is provided, also writes each rewrite to
    `output_dir/proposed_rewrites/{sanitized_name}.rewrite.md`.
    """
    scorecards = scorecards or []
    responsibility = responsibility or []
    benchmark_results = benchmark_results or []
    scorecard_by_name = {s.artifact_name: s for s in scorecards}
    responsibility_by_name = {r.artifact_name: r for r in responsibility}
    benchmark_by_name = {b.artifact_name: b for b in benchmark_results}
    rewrites: dict[str, str] = {}
    for a in artifacts:
        body = generate_rewrite(
            a,
            findings,
            scorecard=scorecard_by_name.get(a.name),
            responsibility=responsibility_by_name.get(a.name),
            benchmark=benchmark_by_name.get(a.name),
        )
        if body is None:
            continue
        rewrites[a.name] = body
        if output_dir is not None:
            target = output_dir / "proposed_rewrites" / f"{_sanitize_name(a.name)}.rewrite.md"
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding="utf-8")
    return rewrites
